### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'daemon'

### ISSUE THREAD

**Issue by mhb8898** [SharifAIChallenge/AIC18-Client-Python#10]
hi
i just got this error
```
➜  AIC18-Client-Python-2.3 python Controller.py
Trying to connect #1
connected to server!
Traceback (most recent call last):
  File "Controller.py", line 87, in <module>
    c.start()
  File "Controller.py", line 30, in start
    self.network.connect()
  File "/Users/nic/Downloads/AIC18-Client-Python-2.3/Network.py", line 45, in connect
    self.start_receiving()
  File "/Users/nic/Downloads/AIC18-Client-Python-2.3/Network.py", line 73, in start_receiving
    tr = threading.Thread(target=run, daemon=False)
TypeError: __init__() got an unexpected keyword argument 'daemon'
```

i use
```
➜  AIC18-Client-Python-2.3 python --version
Python 2.7.10
```

**Comment by ali-behjati** [comment]
You should run the client using python 3
